version: "3"

networks:
  external-network:
    driver: bridge
  internal-network:
    driver: bridge

services:

  nginx:
    build: ./nginx
    restart: always
    tty: true
    depends_on:
      - web
    environment: 
      HOSTNAME: ${HOSTNAME}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./web:/web
      - ./nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
      - "443"
    links:
      - web
    networks:
      - internal-network
      - external-network

  web:
    container_name: ctfbwk_web
    build: ./web
    tty: true
    volumes:
      - ./web:/web
    depends_on:
      - mariadb
    ports:
      - "9000"
    links:
      - mariadb
    networks:
      - internal-network

  mariadb:
    container_name: ctfbwk_mariadb
    image: mariadb
    tty: true
    restart: always
    environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_BACKUPS_DIR: ${DB_BACKUPS_DIR}
    volumes:
        - ./mariadb/database.sql:/docker-entrypoint-initdb.d/database.sql
        - mariadb_data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - internal-network

volumes:
  mariadb_data: